version: "3.7"

services:
  mongo:
    image: mongo
    container_name: cap.hc.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - cap_hc_network

  mongo-express:
    image: mongo-express
    container_name: cap.hc.mongoexpress
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: cap.hc.mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - cap_hc_network
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: cap.hc.rabbitmq
    restart: always
    networks:
      - cap_hc_network
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"

networks:
  cap_hc_network:
    name: cap-hc-network
