name: Publish Preview Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.404
    - name: Dotnet Restore
      run: dotnet restore
    - name: Dotnet Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish DotNetCore.CAP.HealthCheck
      uses: ./.github/actions/publish-nuget
      with:
          PACKAGE_NAME: DotNetCore.CAP.HealthCheck
          PROJECT_FILE_PATH: src/DotNetCore.CAP.HealthCheck/DotNetCore.CAP.HealthCheck.csproj
          VERSION_FILE_PATH: build/version.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          VERSION_SUFFIX: preview${{ github.run_number }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish DotNetCore.CAP.HealthCheck.PostgreSql
      uses: ./.github/actions/publish-nuget
      with:
          PACKAGE_NAME: DotNetCore.CAP.HealthCheck.PostgreSql
          PROJECT_FILE_PATH: src/DotNetCore.CAP.HealthCheck.PostgreSql/DotNetCore.CAP.HealthCheck.PostgreSql.csproj
          VERSION_FILE_PATH: build/version.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          VERSION_SUFFIX: preview${{ github.run_number }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish DotNetCore.CAP.HealthCheck.RabbitMQ
      uses: ./.github/actions/publish-nuget
      with:
          PACKAGE_NAME: DotNetCore.CAP.HealthCheck.RabbitMQ
          PROJECT_FILE_PATH: src/DotNetCore.CAP.HealthCheck.RabbitMQ/DotNetCore.CAP.HealthCheck.RabbitMQ.csproj
          VERSION_FILE_PATH: build/version.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          VERSION_SUFFIX: preview${{ github.run_number }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish DotNetCore.CAP.HealthCheck.MongoDB
      uses: ./.github/actions/publish-nuget
      with:
          PACKAGE_NAME: DotNetCore.CAP.HealthCheck.MongoDB
          PROJECT_FILE_PATH: src/DotNetCore.CAP.HealthCheck.MongoDB/DotNetCore.CAP.HealthCheck.MongoDB.csproj
          VERSION_FILE_PATH: build/version.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          VERSION_SUFFIX: preview${{ github.run_number }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
